/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author untuk
 */
public class PanelDataBalita extends javax.swing.JPanel {

    Connection conn = Uas.getKoneksi();
    DefaultTableModel model;
    
    /**
     * Creates new form PanelDataBalita
     */
    public PanelDataBalita() {
        initComponents();

        cmbJenisKelamin.removeAllItems();
        cmbJenisKelamin.addItem("L");
        cmbJenisKelamin.addItem("P");

        tampilData();
    }
    
    public void tampilData() {
        model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Nama Orang Tua");
        model.addColumn("Alamat");
        model.addColumn("No KIA");

        tblBalita.setModel(model);

        try {

            String sql = "SELECT * FROM balita";

            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("id_balita"),
                    rs.getString("nik"),
                    rs.getString("nama"),
                    rs.getDate("tgl_lahir"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("nama_ortu"),
                    rs.getString("alamat"),
                    rs.getString("no_kia")
                });

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan Data\n" + e.getMessage());

        }

    }
    
    public void kosongkanForm() {
        txtNik.setText("");
        txtNama.setText("");
        txtTanggalLahir.setText("");
        txtNamaOrtu.setText("");
        txtAlamat.setText("");
        txtNomorKia.setText("");

        cmbJenisKelamin.setSelectedIndex(0);

        txtNik.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBalita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        txtCariNik = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNamaOrtu = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtNomorKia = new javax.swing.JTextField();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(17, 24, 68));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA BALITA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblBalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBalitaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBalita);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nik");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelamin");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Lahir");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Orang Tua");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nomor Kia");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat ");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtCariNik.setText("Cari Nama NIk.........");

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7)
                                .addGap(115, 115, 115))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNamaOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomorKia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtCariNik, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCari)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambah)
                            .addGap(18, 18, 18)
                            .addComponent(btnEdit)
                            .addGap(18, 18, 18)
                            .addComponent(btnHapus)
                            .addGap(52, 52, 52))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(141, 141, 141)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(131, 131, 131)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(jLabel3)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(txtCariNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNik, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAlamat)
                    .addComponent(txtNamaOrtu)
                    .addComponent(txtNomorKia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
        try {

        String sql = "INSERT INTO balita(nik,nama,tgl_lahir,jenis_kelamin,nama_ortu,alamat,no_kia) VALUES(?,?,?,?,?,?,?)";

        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, txtNik.getText());
        ps.setString(2, txtNama.getText());
        ps.setString(3, txtTanggalLahir.getText());
        ps.setString(4, cmbJenisKelamin.getSelectedItem().toString());
        ps.setString(5, txtNamaOrtu.getText());
        ps.setString(6, txtAlamat.getText());
        ps.setString(7, txtNomorKia.getText());

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");

        kosongkanForm();
        tampilData();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblBalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBalitaMouseClicked

        int baris = tblBalita.getSelectedRow();

        txtNik.setText(model.getValueAt(baris,1).toString());
        txtNama.setText(model.getValueAt(baris,2).toString());
        txtTanggalLahir.setText(model.getValueAt(baris,3).toString());
        cmbJenisKelamin.setSelectedItem(model.getValueAt(baris,4).toString());
        txtNamaOrtu.setText(model.getValueAt(baris,5).toString());
        txtAlamat.setText(model.getValueAt(baris,6).toString());
        txtNomorKia.setText(model.getValueAt(baris,7).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tblBalitaMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {

            String sql = "UPDATE balita SET nama=?, tgl_lahir=?, jenis_kelamin=?, nama_ortu=?, alamat=?, no_kia=? WHERE nik=?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, txtNama.getText());
            ps.setString(2, txtTanggalLahir.getText());
            ps.setString(3, cmbJenisKelamin.getSelectedItem().toString());
            ps.setString(4, txtNamaOrtu.getText());
            ps.setString(5, txtAlamat.getText());
            ps.setString(6, txtNomorKia.getText());
            ps.setString(7, txtNik.getText());

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Data berhasil diubah");

            kosongkanForm();
            tampilData();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,e.getMessage());

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       
        int jawab = JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if(jawab==JOptionPane.YES_OPTION){

            try{

                String sql="DELETE FROM balita WHERE nik=?";

                PreparedStatement ps=conn.prepareStatement(sql);

                ps.setString(1, txtNik.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null,"Data berhasil dihapus");

                kosongkanForm();
                tampilData();

            }catch(Exception e){

                JOptionPane.showMessageDialog(null,e.getMessage());

            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed

        if(txtCariNik.getText().trim().isEmpty()){
            tampilData();
            return;
        }
        model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Nama Orang Tua");
        model.addColumn("Alamat");
        model.addColumn("No KIA");

        tblBalita.setModel(model);

        try{

            String sql="SELECT * FROM balita WHERE nik LIKE ? OR nama LIKE ?";

            PreparedStatement ps=conn.prepareStatement(sql);

            ps.setString(1,"%"+txtCariNik.getText()+"%");
            ps.setString(2,"%"+txtCariNik.getText()+"%");

            ResultSet rs=ps.executeQuery();

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getInt("id_balita"),
                    rs.getString("nik"),
                    rs.getString("nama"),
                    rs.getDate("tgl_lahir"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("nama_ortu"),
                    rs.getString("alamat"),
                    rs.getString("no_kia")

                });

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblBalita;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCariNik;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaOrtu;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNomorKia;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
